/* Goallak service worker
   CACHE changelog (bump on EVERY deploy, newest first):
   goalak-v65  2026-08-18  v6.11 FANTASY IS OPEN TO EVERYONE, AND THE CALENDAR IS NOW THE LOUDEST THING ON THE TEAM SCREEN. The owner opened the game: the holding screen and the owner-only release gate are DELETED, not switched off - along with gk_fx_owner and ?fxowner=1, because a dormant gate is one edit from locking the public out and an earlier version of this one locked out the owner himself. A commit gate now refuses the code shapes if they return, and the QA suite runs with EMPTY storage and no account, so 208 assertions prove a stranger reaches the game rather than proving an unlocked owner does. THE WEEKLY DECISION IS NOW SAID OUT LOUD. A backtest of the real 2025-26 season settled what actually matters week to week here, and it is not form - chasing the last five rounds cost 105 points across a season. It is the calendar: a blank starter scores zero, a club playing twice scores roughly double, and both are KNOWN at the deadline. That was a whisper on a card you had to go looking for; it is now a band above the pitch with four states - calm, doubles, blanks, and a red line for the worst case, a BLANKED CAPTAIN, which is the biggest single loss a round can hand you and the one the auto-sub cannot rescue. It opens the whole squad sorted by what each club does this round, one tap from the fix. AND THE -4 STAYS AT -4, measured rather than argued: swapping your coldest club for the hottest available is worth 3.17 points a round and works 97% of the time, while upgrading your cheapest for the dearest is worth 5.07 - so -4 sits exactly between them, deterring form-chasing while still paying for a real quality upgrade. Sweeping the hit from -4 to -12 and the bank from 5 to 1 moved the season by under 1%, so raising it would have been cosmetic. 18 new live assertions on the band, all four states in both languages, mutation-checked; 208 live, 1,565 across the modules.
   goalak-v64  2026-08-18  v6.10 LEAGUE MATCHES ONLY. The owner's rule, and it overrides yesterday's measurement: "it should be only the league matches not europa league not champions league nothing!" v6.9 had widened the fixture feed to 32 competitions because 769 of our clubs' 3,023 matches in 2025-26 were played outside the seven leagues. The count was right and the decision is still wrong for this game - it is the Premier League game's own rule, and it is the legible one: one table, one fixture list, one meaning for 'plays this round'. It also mattered mechanically, because counting the cups filled nearly every blank week and so quietly deleted the hold-or-pay decision the transfer economy had just been built around. Back to seven feeds: blanks 6.86% of club-rounds, doubles 4.39%. WHAT DOES NOT GET UNDONE is the bug the wide version exposed - the slug list was a top-level const reading LEAGUES, which clubs.json fills in AFTER the script parses, so it evaluated to the empty array and every league match disappeared while the code read perfectly; round 1 returned 42 of 126 clubs playing. The slugs are gathered when the fetch runs, and the commit gate now refuses both the parse-time shape and any non-league slug. Dedupe by event id stays too: seven league feeds cannot overlap today, but counting one match twice would report a double where there is one game, which is the most expensive way this screen can be wrong.
   goalak-v63  2026-08-18  v6.9 A TRANSFER NOW COSTS SOMETHING, AND ONE MATCH IN FOUR WAS INVISIBLE. The owner asked what changing his whole team between rounds costs, and the honest answer was NOTHING - unlimited, free, every round. That made chasing form strictly correct, made the four bench slots pointless, and made four of the eight chips promises about a system that did not exist: the Wildcard's own shipped copy offered transfers with no -4 in a game that had no -4. One free transfer a round now, banked up to five, -4 for each one beyond that, and Wildcard and Free Hit lift the charge exactly as their copy always said. The free build belongs to the MANAGER, not the calendar - the owner's rule, and the right one: somebody joining at round twelve is building a first squad like anybody else, and charging him would cost 56 points for arriving late. Rounds elapsed while the app is closed still bank. THE SECOND FIX IS BIGGER: fixtures were read from the seven LEAGUE feeds only, so measured across 2025-26, 769 of our clubs' 3,023 matches were invisible - 171 Champions League ties, 130 Europa, 65 Copa del Rey, down to the Community Shield - and the clubs worst hit, up to 25 matches each, were the expensive ones a manager pays for. A Barcelona European night read as 'Rest' and scored zero. All 215 competitions Goallak knows were swept: 26 feeds now, ties deduped by event id, and coverage is 3,023 of 3,023. What stays out is out on purpose and written down - friendlies, second divisions, and the Challenge Cup that colt sides enter. Blanks are also no longer BLOCKED, on the owner's argument: once a transfer costs points, keeping a club through a quiet round instead of paying -4 out and -4 back is a real decision, and the app now says 'no match' or 'plays 2' on the row BEFORE the tap. The tutorial no longer gives away that four superclubs never fit - that is the puzzle, not the briefing. 33 new assertions on the economy, mutation-checked; 1,563 across the modules; 190 live; two new commit gates.
   goalak-v62  2026-08-18  v6.8 NAME THE CLUB YOU CARE ABOUT, WE BUILD THE REST. Fifteen taps is data entry, and the owner named the fix: let a player choose one or two clubs and complete the squad around them. One tap from the moment he owns his first club, and from every picking step after it - he can stop at one club or at ten. His own choices are never dropped to make the budget work, never reordered out of the eleven, and everything stays editable, including on the captain step where a generated squad is first seen in full. It fills by VALUE and then spends what is left upgrading the clubs he did not choose: the generator this replaces ranked candidates on a fame field the scoring engine never reads, and the squad it produced finished last of six in a measured season. Where strength data is missing it falls back to PRICE, which the five-season backtest puts against real points at r = 0.967 - the first version used 1/price instead, built the cheapest legal squad in the game and handed back 50M, which its own new test caught. Verified across all 126 clubs as the seed: a legal fifteen every time, the seed kept every time, and never less than 110M spent.
   goalak-v61  2026-08-18  v6.7 THE DOUBLES ARE NOT A FLAW, AND ONE OF THEM WAS MY BUG. A study across the published 2026-27 fixture list and five reconciled seasons settles it. Blanks and doubles are ONE quantity, tied by an identity verified with zero mismatches over ten calendar reconstructions - you cannot cut one without raising the other, which is why rebuilding the calendar could never have worked. Doubles are unavoidable arithmetic: 38 matches cannot fit in 36 rounds, so 3.2-4.8% of club-rounds must be doubles under ANY calendar, and the live season's rate sits barely above its own floor. Decisively, with a fixed eleven a squad's season total is INVARIANT to the calendar - measured difference exactly zero - so doubles can only touch auto-subs, the armband and lineup choice. Across 15,000 simulated squads club quality explains 78.1% of season variance and double exposure 0.6%, a 126:1 ratio; a squad that chases doubles while ignoring quality scores 8.7% WORSE, and perfect doubles play is worth +2.74% of which all is readable at the deadline. Our 4.28% is parity with the Premier League's own game at 4.50%. THE REAL BUG WAS MINE: ESPN's date range is inclusive at both ends while consecutive rounds share an endpoint, so every fixture on a boundary date was counted in TWO rounds - inflating doubles to 5.05% and making round 1 appear to hold 15 matches with 11 clubs doubled and Rayo idle ALONE. Half-open now, and the truth is 13 matches, 8 doubled, and TWO idle - Alaves and Rayo, a pair, exactly as the owner reasoned it had to be.
   goalak-v60  2026-08-18  v6.6 A ROUND COUNTS MATCHES, NOT WHETHER THERE IS ONE. The owner spotted that Rayo was the only La Liga club with no fixture in round 1 and reasoned - correctly - that a fixture needs two clubs, so blanks in a league must come in pairs. The pairing logic is right; the WINDOW is what breaks it. A round is a slice of time, not a matchday, and the seven leagues start four weeks apart: Scotland 31 Jul, Turkey 14 Aug, Spain 15 Aug, England and France 21 Aug, Italy 22 Aug, Germany 28 Aug. Round 1 opens on 21 Aug, so La Liga's first six days are already behind it and the window catches parts of two matchdays - measured, 15 matches with ELEVEN of twenty clubs playing twice, and Rayo idle for eight days purely because its games sit either side. From round 3 onward the same calendar is exact: 10 matches, nobody idle, nobody doubled. So this is a season-boundary artefact, not a broken calendar, and rebuilding the calendar was tried and made it worse across the season (blanks 9.1% -> 9.6-12.7%), so it was reverted. What was wrong is that the app recorded only WHETHER a club plays. Two matches is worth roughly double, so it now counts them and the card says 'plays 2'. Still open and recorded: the simulator scores at most one fixture a round.
   goalak-v59  2026-08-17  v6.5 THE TUTORIAL TEACHES BY MAKING YOU DO IT. v1 generated a fifteen-club squad, showed it to the player, taught one swap gesture on somebody else's team and never mentioned the chips at all - then the app threw that squad away, so the lesson had no connection to the team he ended up with. Eight steps now - welcome, first club, budget, the eleven, the bench, the captain, the chips, done - and the pitch starts EMPTY. The fifteen clubs he taps ARE the team he owns; nothing is generated, and tutBuildSquad, tutFavouritePool and the seeded generator are deleted rather than left dormant. The spine is the gate: a step that teaches an action renders no forward control until the action is done, and NEXT on an unmet gate returns the state untouched. Counts advance themselves at the first club, the eleventh and the fifteenth; choices reveal the way on instead, so tapping a chip to READ it is not punished. The chips are taught for the first time - four families, two per half, each card opening to say what it does and when to use it, with copy compared character by character against chips.js so the duplicate cannot drift. Replaying still costs nothing: the wizard is handed the player's existing squad, so a replay is nine taps and he keeps his team. 76 module assertions, 190 in the live suite.
   goalak-v58  2026-08-17  v6.4 THE REPRICE BROKE THE TUTORIAL'S SQUAD BUILDER AND IT WAS LIVE. Same bug as the app's budget reserve, in a second place: both the band phase and the backfill assumed a remaining slot could always be filled at the floor price, which the three-per-league cap makes false now only eleven clubs sit at 4.5 and they span four leagues. The builder was stranding on 13 clubs for several favourites and reporting a squad it could not finish - eight of its own 54 assertions were failing. Both phases now test the real cheapest completion with the candidate already owned. Also structural: the module SOURCES move into this repo under fantasy/src, so there is finally one copy of everything - the last edits lost today were all caused by a source here and a source there.
   goalak-v57  2026-08-17  v6.3 FIVE SEASONS SETTLE THE PRICES. 11,569 matches across 2021-22 to 2025-26, 34 of 35 league-seasons reconciling against ESPN's standings with zero discrepancies. The goal/clean-sheet correction holds - the old rules dipped 1.29 points at the second goal in EVERY season, range 0.09, so it was never noise. The league premium is STRUCTURAL: England last in points per million in all five seasons (25.68, SD 0.51), Turkey first in all five (40.10), surviving both a survivorship and a rank-matched control; a top-four finish returns 9-10 points a match in every league and costs 14.0M in England against 8.9M in Turkey. Intended premium 9.1%, realised 56.2%. League multipliers applied - eng 0.820, esp 0.950, ita 1.013, ger 1.034, fra 1.070, tur 1.175, sco 1.101 - and the four superclubs keep a deliberate demand premium on top so no four of them fit, which is a balance lever and not a value correction. A CLAIM IN THE CODE WAS WRONG AND IS CORRECTED: the 6/3/0/0 opponent bonus was justified by a correlation gain measured on one season that does not replicate; it is kept for a design reason instead. The reprice also exposed a real bug - the budget reserve assumed every remaining slot could be filled at the floor price, which the three-per-league cap makes false once only eleven clubs sit at 4.5, so a squad could be built that could not be finished. Affordability now means COMPLETABLE. And twelve Arabic club names cannot fit a 76px card at any legible size, so those twelve carry a short form a commentator would actually use.
   goalak-v56  2026-08-17  v6.2 IT SAID ROUND 6 IN AUGUST. CURRENT_GW was pinned to 6 - a leftover from when the season was something to scrub through - so the app announced round six four days before round one had opened, and the round bar, the lock and the tutorial all repeated it. The round is read from the calendar now: the window containing today, round 1 before the season starts, the last round after it ends. Verified against the shipped dates: 17 Aug gives round 1, 22 Aug round 1, 30 Sep round 6, 20 Jun round 36. A round the user has deliberately scrubbed to still wins, but nothing is hard-coded. Also: two buttons sat together in settings reading 'watch the explanation from the start' and 'start from the start' - near-identical in Arabic, and one of them silently deletes your team. They now say what they each do: 'start the tutorial again' and 'delete my team and start again'.
   goalak-v55  2026-08-17  v6.1 NOTHING CALLS ITSELF A DEMO ANY MORE. The standing disclaimer - 'Demo build for review only, the points are simulated to show the design' - was still being printed under the settings sheet and on the empty points screen. It had been rewritten once and then reappeared when the file was re-synced from an older copy, which is the same two-sources problem that cost the owner gate. Every renderable string is now checked: none contains the word. Gone with it: the DEMO suffix in the page title, the unused DEMO chip style, the stale 'resets on every open' comment describing behaviour removed days ago, and 'Reset demo' which is now 'Start over'. The empty points screen says what is actually true - you have not picked a team yet - and the season's own state is already stated by the round card, so no disclaimer is needed to say it twice.
   goalak-v54  2026-08-17  v6.0 THE SCORING WAS BACKTESTED AGAINST A REAL SEASON AND TWO NUMBERS WERE WRONG. 2025-26 rebuilt across all seven leagues - 2,285 matches, 4,570 club performances, reconciled EXACTLY against ESPN's own tables on played, W/D/L, GF and GA. The ordering held up: rank correlation with the real final tables 0.985 pooled, no club displaced by more than four places. But the system was NOT MONOTONIC IN GOALS: mean points for a win were 11.00 by one goal, 9.69 by two, 10.23 by three - scoring your second goal COST you 1.31 points, and 763 of 1,314 multi-goal wins (58.1%) paid less than a 1-0. A clean sheet at +4 was worth four goals, so a win's points correlated +0.12 with goals scored and -0.75 with goals conceded. Goal +1 -> +2 and clean sheet +4 -> +3 restores monotonicity and lifts that correlation to +0.71, chosen from a 540-combination grid as the best set that keeps the clean sheet meaningful (12.9% of all points rather than 20.9%); it also improves the price fit and the signal-to-noise. The opponent bonus was near-inert at 7.0% of points, its +1 band spread over 575 wins; 6/3/0/0 concentrates it and lifts the worst league's rank correlation 0.935 -> 0.955. Win 6, draw 2, -1 per two conceded, the spread and the superclub prices all tested clean and are untouched. Still open and recorded in the report: pts-per-million differs by league (English 20.8 vs Scottish 31.2) and the optimal legal eleven contains no Premier League club, but one season cannot prove that is structural, so no price moved on it.
   goalak-v53  2026-08-17  v5.9 THE SEASON MAP AND THE SCORING TABLE. Settings now opens all 36 round windows with their real dates from the frozen calendar, the current round highlighted, the long windows marked with their length and the rounds where a lot of clubs sit out marked with their coverage - those are exactly the weeks a badly chosen bench costs points. And the help screen, which explained the whole game without ever printing a single number, now states the scoring outright: win +6, draw +2, loss 0, each goal scored +1, clean sheet +4, every two goals conceded -1, beating a strong side +1 to +3, captain doubled, no match 0 - with a worked example, because a scoring system nobody can find is a scoring system nobody trusts.
   goalak-v52  2026-08-17  v5.8 THE SUPERCLUB LOOPHOLE IS CLOSED AND SETTINGS MOVES TO THE NAV. Raising only the four named clubs left a hole: Man City and PSG were both 15.0, so three of the four plus one of those was 66.0 and completed a squad at 115.5 inside 120 - four superclubs, just not the four that had been repriced. Both go to 18.0, which makes the CHEAPEST four clubs at or above 15.0M cost 72.0 and need 121.5 with eleven floor clubs: no four of them fit, whichever four you choose, while any three still fit at 107.5. Settings leaves the header for the bottom navigation where the owner asked for it; six items now, so the labels are sized to survive 60px at a 360px viewport.
   goalak-v51  2026-08-17  v5.7 THE TUTORIAL WAS LYING ABOUT DATES, AND THE BIG FOUR GET A PREMIUM. (1) One tutorial card carried three separate falsehoods that contradicted each other: the heading read the round the app was really on, the body read 'Round 1: Fri 21 Aug to Sun 23 Aug' from two hardcoded strings, and the lock read 'Fri 8:30pm' - a kick-off time this product does not have and never has. Round 1 actually runs 21 to 28 August, so even the hardcoded pair was wrong about the round it claimed to describe. Every date now comes from the frozen calendar and the lock is stated as a DATE, because a date is what we know. (2) All four superclubs could be owned at once: 18.5 + 17.5 + 16.5 + 15.5 = 68, and eleven clubs at the 4.5 floor is 49.5, so the squad completed at 117.5 inside a 120 budget with change to spare. Arsenal 20.0, Bayern 19.0, Barcelona 18.5, Real Madrid 17.5 puts four of them at 124.5 - impossible - while any three still fit at 109 to 111.5. Their points are untouched, so the premium is real: they cost more for the same return, which is what makes picking three of them a decision instead of an obvious yes.
   goalak-v50  2026-08-17  v5.6 THE WAY OUT SAYS WHERE IT GOES, AND THE LESSON CAN BE REPLAYED. (1) An arrow on its own is a guess. The back control is now a labelled bar directly under the header reading 'the return to the Goallak app', full width, where a back control belongs on a page that is not a tab. (2) Replaying the walkthrough must not cost you your team: reset wipes everything, which is right for starting over and wrong for wanting to see the lesson again. A replay control in settings clears only the flag that says you have seen it, and /fantasy/?tutorial=1 does the same without hunting through a sheet. (3) check.mjs now refuses duplicate ids: the replacement back control was added without the old one being removed, so the page carried two, and getElementById returns the first - the code updates one node while the other is the one on screen.
   goalak-v49  2026-08-17  v5.5 THE BLANK IS REAL NOW. Which clubs have no match was decided by a bit of the club-id hash - fiction dressed as a fixture, the same class of thing as the simulated points, and it was driving a decision the player makes. The round's fixtures now come from ESPN: one request per league covers a whole round because the API accepts a date RANGE, so a round costs 7 requests and is cached. Only the club's OWN league counts, which is exactly how the Premier League's game defines a blank - a cup tie is a match but it is not a league match, and league results are what this game scores. The picker refuses a club with no fixture, as the owner asked, but ONLY on a known absence: while the answer is loading the app claims nothing, because an unknown fixture must never look like a confirmed one, and an empty response is treated as a failed feed rather than as proof that nobody plays. The card's second line stops naming an invented opponent and says only whether the club plays, which is the part that is actually known.
   goalak-v48  2026-08-17  v5.4 THE BACK BUTTON, THE ROUND LOCK, AND THE VERSION MARKER. (1) The back control was referenced by the code and never existed in the markup - an edit script raised before its final write, so the reference landed and the element did not, and because the reference sat in a try/catch the page carried on and the button was simply absent. check.mjs now REFUSES any commit where the script reads an id no element has. (2) The round now LOCKS. A fantasy without a cut-off is not a game: you could watch a result and then buy the club that produced it. The Premier League's own game locks 90 minutes before the first kick-off and freezes the eleven, the armband and every transfer until the round ends, with later changes applying to the NEXT round. We hold dates rather than kick-off times, so the lock is the moment the round's window opens - stricter than a 90-minute cushion and never later than the first match, which is the safe direction to be wrong in. The picker, every swap and the captain sheet all pass through one gate. (3) APP_VERSION had been left at 4.6 through eight releases; it is the marker the owner reads to know what he is looking at, and it now says 5.4.
   goalak-v47  2026-08-17  v5.3 THE OWNER GATE WAS LOST AND IS NOW IN THE SOURCE. v4.8 added it by editing the DEPLOYED copy of index.html and never the working source, so when v5.1 copied the source over to ship the cross-competition fixtures it wiped the gate out entirely - the Fantasy tab then had no way in for anybody, the owner included. It lives in the source now, which is the only copy anything is built from. Two other changes: the owner match is deliberately generous, letters only and any username CONTAINING the family name, because an exact-spelling list locked the one person it exists for out of his own product; and when somebody is signed in and still shut out the screen names the account it is judging, so the only way to debug it is not to ask him to guess his own username.
   goalak-v46  2026-08-17  v5.2 FANTASY: real club crests, no invented opponents, the app's own leaderboard and the app's own language. 124 of 126 clubs carry their real crest, self-hosted at 128px - which is 22x LIGHTER than hotlinking, not heavier, because ESPN only publishes the 500px original at ~66KB and sends a 55-second cache header so a hotlinked crest never really caches. Amed SFK and Corum FK have no logo at ESPN at all (empty logos array, hard 404); their ids are correct, they are absent from the manifest and fall back to kit-and-code. The crest sits on a neutral chip because it would otherwise sit on the club's OWN colour, which is usually the crest's colour too - 71 of 124 have over 30% of their artwork within 1.5:1 of their kit and four are at 100%, so Liverpool's liver bird on its red would be a blank red rectangle. onerror removes the CHIP rather than the image, so a failure leaves no empty disc and shifts nothing. The five rivals were invented people - hardcoded names so the demo had someone to sit against, all on zero now the season has not started, i.e. a fabricated league presented as standings; the list is empty and says so. The standings now mirror the app's own card and rows instead of looking like a different product. And fantasy kept its own language, so the English app opened an Arabic game; it inherits the app's language on first open.
   goalak-v45  2026-08-17  v5.1 EVERY MATCH FOR THE TOP CLUBS, IN EVERY COMPETITION. The app fetched a fixed set of LEAGUE scoreboards, so a big club's cup tie simply did not exist - Barcelona v Al Ahly on 19 Aug sits in competition 17929 and appeared nowhere, not even under friendlies. It now also reads ESPN's cross-competition scoreboard and keeps any fixture involving a club that finished top five in its league LAST SEASON (2025-26, ESPN season=2025 - verified from completed tables, 38 games played in ENG/ESP/ITA/SCO and 34 in GER/FRA/TUR, not assumed). 35 clubs, 215 competition ids mapped to names so a cup match is never unlabelled. TWO TIERS BECAUSE COST: the cross-competition feed carries no competition name and is heavy, so discovery runs once per calendar date on a 10-minute cache and each competition found is then read from its own small scoreboard at the normal live cadence - cup scores stay as fresh as league scores without re-downloading 300KB every 25 seconds. limit=300 is mandatory there too: a 3-day range silently returns exactly 100 events without it, the same truncation the World Cup app was bitten by. De-duplication has three guards (slug, event id, and fixture key across groups) and was swept over 9 days with zero duplicates, including the documented Como/Liverpool ghost twin which still collapses to one row. FAIL-SOFT PROVEN: with every extra call throwing, and again with top-clubs.js deleted, the list is byte-identical to before - the failure never reaches dayFailed and the cache is written even when empty, because a MISSING cache is what turns an empty day into a red error box. A 40-day sweep of 6,056 events found 29 previously invisible fixtures across 9 competitions now showing: Arsenal in the Emirates Cup and Community Shield, PSG and Aston Villa in the UEFA Super Cup, Bayern and Dortmund in the German Supercup and DFB-Pokal, and five Scottish clubs in the League Cup and Conference League qualifiers.
   goalak-v40  2026-08-16  v4.6 ACCESSIBILITY + WRITE LOCK, ahead of Fantasy becoming a real feature. (1) LIGHT-THEME CONTRAST: light is the DEFAULT theme precisely because it is the readable one for older eyes, and three of its tokens did not clear WCAG AA against the grounds they actually land on. Measured, not guessed: --acc #c2451b was 4.46/5.05/4.22 on bg/card/card2 -> now #b03f18 at 5.20/5.88/4.92; --dim2 #6b7a9c was 3.80/4.30/3.60, failing on ALL THREE grounds and used for every secondary label -> now #5c6a89 at 4.79/5.42/4.53; --gold #946400 was 4.31 on card2 -> now #8a5d00 at 4.82. Dark theme was already clear (worst token 5.44) and is untouched. (2) REDUCED MOTION: the app honoured the OS "reduce motion" switch nowhere. Decorative animation (the live pulse dot, the recording pulse) now stops and transitions collapse; the SPINNER deliberately keeps turning, slowly, because it is the only signal that a fetch is still running and freezing it would read as a hung app. (3) KEYBOARD FOCUS: there was not a single :focus rule in the stylesheet. Added a :focus-visible ring (gold, offset) so a tap still paints nothing but a keyboard or switch user always knows where they are. (4) FOCUS TRAPPING: sheets were visual-only - Tab walked straight out of an open match sheet into the match list behind it, and a screen reader could wander the whole page while a modal covered it. One trap at the lowest common layer, driven by the SAME topmost-sheet order Escape already uses, so any future sheet inherits it; sheets now carry role=dialog + aria-modal, focus moves into the panel on open and returns to whatever opened it on close. (5) WORKER: the /tdb proxy answered POST with Access-Control-Allow-Origin:* , so any page on the internet could script writes into the accounts/predictions/leaderboard store through it. Writes are now locked to https://goallak.com - not localhost, not a missing Origin. This does NOT make that data safe (textdb.online is world-writable by design and a server-side client can still write to it directly); it closes the easy browser path. The real fix, needed before Fantasy ships, is moving accounts + predictions behind the worker with server-side auth the way chat already works.
   goalak-v39  2026-08-16  v4.5 LESSONS-LEARNED AUDIT FIXES. A dedicated audit of this app against the WC app's LESSONS_LEARNED, the pre-deploy checklist and the WC sw.js bug changelog found 7 violations and 12 partials; 5 of the 7 were the SAME failure mode - a fix applied to some surfaces and not all. Fixed: (BLOCKER) the midnight live bug was still live one layer down - the strip/chip/count were state-gated in v4.2 but the LIVE LIST and the MATCH SHEET keyed off _gkLeagueId, which was written only inside mrow() i.e. only for the browsed day, so a match that kicked off before midnight showed "live (1)" beside an empty list and opened with no timeline, line-ups, stats, Star of the Match or TV channel; events are now tagged where they are CACHED, one writer, so every consumer sees them. (HIGH) .pname was declared bare for the pitch and reused by the leaderboard podium - in LIGHT theme the 2nd and 3rd place names were white on white, invisible; the pitch class is renamed .gkPname (the .msg collision, third occurrence). (HIGH) Serie A existed in the app but never in the push worker, so Serie A alerts were dead and anyone who selected only Serie A got zero notifications with the toggle showing ON. (HIGH) "failed" was being rendered as "empty" in three more places: a failed prediction read scored a real player 0 points, a failed standings fetch was persisted as "this league has no clubs" for SEVEN DAYS (breaking the favourite-club picker and the friendlies filter), and an empty chat history overwrote the local cache. (HIGH) saveClubToAccount rewrote the whole shared accounts object with no wipe guard and no verify-after-write - a signup landing between its read and write was erased; it now uses the same 3-attempt guarded loop as doAuth. (HIGH) not one ESPN scoreboard call sent &limit=, the exact bug that hid an entire knockout round in the WC app (v3.31) - club friendlies were already at 60 of the silent 100-event cap; all six calls now go through one sbUrl() helper. Also: the day now follows midnight on RESUME, not just while the tab is visible (an installed app is backgrounded across midnight every night); the leaderboard's Math.min(150) would have started silently decaying every player's total from 2026-12-29 - the cap is gone and the season anchor, the previous-season chip and the season labels are all derived instead of hardcoded; the footer version marker is driven from APP_VERSION instead of hand-typed; five aria-labels and the AM·PM/24H buttons are localised; Escape closes only the topmost sheet and the player card and sign-in sheet push history entries so Back stops eating the tab's entry; a live match no longer appears in BOTH Upcoming and Results; the player card follows a language change; a cross-midnight match keeps its TV channel; .mx got an explicit z-index; and sw.js is never served by itself.
   goalak-v38  2026-08-16  v4.4 STALE-APP FIX (root cause of "my app still shows the old version"): GitHub Pages serves sw.js with Cache-Control max-age=600, so update checks were being answered from the HTTP cache - the browser never saw a new worker, so controllerchange never fired and FORCE_RELOAD never ran. Now registered with updateViaCache:"none" so the worker script is always revalidated. A home-screen app that is only resumed never navigates either, so it now calls registration.update() on resume/focus and every 5 minutes. Plus an independent last-resort guard: fetch index.html no-store, compare APP_VERSION, and reload ONCE (guarded per version in sessionStorage) if this client is behind - so a stuck client recovers even if the service worker misbehaves.
   goalak-v37  2026-08-16  v4.3: FORCE_RELOAD token bumped to 2026-08-16-v43 - it had been stuck on the v3.3 token, so nobody with the app already open (or installed to the home screen) had been forced to refresh through nine releases. Every existing client now hard-reloads exactly ONCE on this update and lands on v4.3.
   goalak-v36  2026-08-16  v4.2: (1) REPEAT OF WC LESSON v2.66 - a match that kicked off before midnight vanished from LIVE at 00:00 because the live set was filtered by calendar day. The live set is now gated on STATE ONLY and spans today + yesterday, for the strip, the LIVE chip, the count and the filtered list; both days are also kept warm by the refresh tick whatever day is on screen. (2) Scroll no longer chains from an open sheet into the page behind it: overscroll-behavior:contain plus a real body scroll lock that restores the exact scroll position on close. (3) Serie A added (ita.1) with Arabic names for all 20 clubs.
   goalak-v35  2026-08-16  v4.1: 3D icon set. All five bottom-nav icons become layered-gradient SVG with a separate active state (white + gold on the rust pill), and the emoji that varied by platform (⚽ 🟨 🟥 in the timeline, scorer lines and match events) become inline 3D symbols. One sprite of gradients + symbols, all gk3d- prefixed, ~2.7KB gzipped, no SVG filters so Android WebView stays fast. The chat bubble was redrawn with a centred tail so it is identical when mirrored for Arabic.
   goalak-v34  2026-08-15  v4.0 QA sweep fixes: (HIGH) Arabic match sheet showed the score one way in the header and the other way in the timeline - running scores and the FT marker now follow the same orientation; (HIGH) a LIVE friendly/international was invisible in the LIVE strip, chip and count because those groups were filtered out - LIVE now covers every competition; (HIGH) ESPN returns subbedIn/subbedOut as objects, so a whole pre-match XI was flagged as substituted on AND off - the flag is read properly now; (MED) league lists refresh every 20s once a match has kicked off instead of holding an ESPN snapshot for 90s; (MED) tab->tab navigation replaces its history entry so Back never needs repeated presses; (MED) substitutes are no longer all rated with the midfield model - a role is inferred from what they actually did; de-duplication now keeps a genuine same-day double-header (different venues, hours apart) while still collapsing ESPN's ghost records; chat send button + chat bar strings localise at boot; Star of the Match keeps the player's position.
   goalak-v33  2026-08-15  v3.9: tap any player (on the pitch or in the line-up list) for a card with his ESPN match kit, rating and full stat line; the Star of the Match card now leads with that kit image too. ESPN has NO player headshots for football (verified: 91 of 92 athlete ids 404 on the headshot pattern) but DOES ship a per-match rendered jersey PNG in light and dark variants (42/42 coverage) - they are 1440px/~218KB and cannot be resized, so they are used only where one image earns its weight (star card + on-demand player card), never 22-at-once on the pitch. Also: settings sheet showed a stale hardcoded v3.2, and .pchip/.lnrow were being re-declared in a second CSS section (the .msg-collision pattern) - both fixed.
   goalak-v32  2026-08-15  v3.8: (a) you can DELETE your own chat messages - trash icon on your bubbles, confirm, removed for everyone (worker re-checks ownership server-side and drops the R2 media too, live "delete" event over the socket); (b) voice notes now PREVIEW before upload - play it back, then Send or bin it, nothing leaves the phone until you press send; (c) de-duplicate fixtures: ESPN published Liverpool v Como twice (a ghost 10:30Z record with no venue next to the real 17:00Z one at Anfield) - same teams on the same day now collapse to the better-sourced record (venue > live/finished > broadcast/odds detail).
   goalak-v31  2026-08-15  v3.7: line-ups now appear BEFORE kick-off like the WC app - tapping a scheduled match opens the pitch as soon as ESPN publishes the XI (roughly an hour before), with a "line-ups usually appear about an hour before kick-off" note until then. A pre-match summary with no XI yet is re-checked every 2 minutes instead of being cached empty for the session, and match rows within 90 minutes of kick-off carry a التشكيل hint.
   goalak-v30  2026-08-15  v3.6 QA-sweep fixes: BLOCKER penalty-shootout kicks were listed as goals under each club (5 "goals" beside a 1-1 scoreline) - now excluded like the timeline already did; Android Back no longer exits the app from Predictions/Fantasy/Chat/Settings (each tab pushes a history entry, Back returns to Matches); alerts toggle localised (إيقاف/تشغيل); 9 top-division clubs added to the Arabic name map (هال، ديبورتيفو، ملقا، إلفرسبرغ، بادربورن، شالكه، لوهافر، لومان، تروا); day-key arithmetic moved to UTC so picking a zone west of the device no longer shifts the date strip by a day; a deep link while Chat/Settings was open no longer renders two panes; leaderboard shows a specific "results unavailable" banner instead of a generic load error; chat badge no longer clips its icon; the day auto-advances at midnight; player ratings now derive goal difference from the scoreline so team-mates are judged on the same rule; aria-labels localised and the settings gear got an accessible name.
   goalak-v29  2026-08-15  v3.5: Summary is now the WC app's TWO-SIDED timeline - centre spine, home events on one side and away on the other, newest first, running score under each goal, substitutions included, goal rows tinted on the scoring side, and the whole thing mirrored for Arabic. Line-ups: subs lists stack full-width on phones and each carries its club name, so nothing needs sideways reading.
   goalak-v28  2026-08-15  v3.4: owner call - the "unofficial app" line is gone entirely (footer is now just brand · motto · version); string, markup and both JS setters removed, nothing left anywhere in the app.
   goalak-v27  2026-08-15  v3.3: FIX bottom-nav labels stayed Arabic on a fresh English load (they were only repainted on a language CHANGE, never at boot) - all five labels now come from one paintNavLabels() used by boot and setLang. Also ported the WC app's FORCE_RELOAD token: bump it and every already-open client hard-reloads exactly once.
   goalak-v26  2026-08-15  v3.2 owner pass: (1) bottom nav rebuilt around a big raised centre orb for MATCHES - Predictions + Fantasy on one side, Chat + Settings on the other, and Settings is now a full page instead of a dropdown; (2) tapping a date shows a spinner while that day is still fetching (it used to flash "no matches / retry" before the data landed); (3) Line-ups now render the REAL pitch from the WC app (formation string -> depth lines -> football-sensible lanes, per-player rating badges and goal/card icons on the shirt, subs listed underneath), goal scorers are listed under each club in the match header, and the stats tab is a proper aligned card with fixed side columns.
   goalak-v25  2026-08-15  v3.1: owner call - drop all data-source name-dropping from the UI. Footer is just "تطبيق غير رسمي", and the TV row shows the channel alone with no "Source: FilGoal/Yallakora" link. Sourcing still happens exactly as before behind the scenes.
   goalak-v24  2026-08-15  v3.0: STAR OF THE MATCH + player ratings, ported from the WC app's engine and re-tuned for club data (club feeds have no xG/xA/duels and sparse tackles, so weight moved to goals, assists, key passes, defensiveInterventions, save% and clean sheets; keeper save-volume now has diminishing returns and keepers take a share of a defeat - a keeper with 11 saves in a 4-1 loss no longer outranks a brace). Ratings show per player in Line-ups; runners-up listed, and a near-tie is labelled instead of faking certainty. Cached per match in localStorage. Verified: GAL 4-1 COR -> Osimhen 9.7; DUN 2-0 ABE -> Bevan 8.6 (goal + assist).
   goalak-v23  2026-08-15  v2.9: tapping a played or in-play match now opens a tabbed detail sheet - Summary (goal/card timeline with assists), Line-ups (both formations, starting XI + used subs with jersey, position, goals/assists/cards/sub minute) and Stats (possession, shots, on target, corners, saves, fouls, offsides, passes, cards as comparison bars). Data from the ESPN match summary feed, cached per match, graceful when line-ups are not published yet.
   goalak-v22  2026-08-15  v2.8: Yallakora is the exact-channel fallback for FilGoal, broadcaster names remain channel-neutral, and predictions explain that they begin after UCL qualifying.
   goalak-v21  2026-08-15  v2.7: club friendlies are limited to fixtures involving at least one club from a tracked Goallak domestic league, reducing load and clutter.
   goalak-v20  2026-08-15  v2.6: club friendlies plus senior national-team official and friendly matches appear in All only; chat names now show each user's favourite club.
   goalak-v19  2026-08-15  v2.5: named TV channels are now shown only for exact fixture matches; league-rights fallback is labelled channel not confirmed instead of claiming a generic broadcaster.
   goalak-v18  2026-08-15  v2.4: selecting match-alert leagues no longer closes Settings after the league buttons re-render.
   goalak-v17  2026-08-15  v2.3: active live-match score refresh reduced from about 45 seconds to about 25 seconds; non-live schedules remain throttled.
   goalak-v16  2026-08-15  v2.2: MENA TV channels with verified rights fallback; mobile chat/header overlap fixes; renewable secure chat session; 1200x630 WhatsApp cover cache-bust.
   goalak-v15  2026-08-15  v2.1: Arabic UI wordmark is جولك; explicit wrong-username/wrong-password login feedback; WhatsApp/Open Graph social cover and feature description.
   goalak-v14  2026-08-15  v2.0: real-time Cloudflare chat, protected picture/video/voice-note media, secure chat sessions, and chat notifications.
   goalak-v13  2026-08-15  v1.9: public rebrand from Goalak to Goallak and custom-domain cutover to goallak.com; technical goalak_* namespaces retained for continuity.
   goalak-v12  2026-08-15  v1.8: chat is members-only (signed-out users see a sign-in wall, no room reads, badge hidden); stats hero tiles overlap fix (owner screenshot: big number over the team name - text now reserves the number's corner and ellipses).
   goalak-v11  2026-08-15  v1.7: permanent "🏆 توقعات دوري أبطال أوروبا" banner at the top of the predictions tab (owner: the tab must say it is UCL).
   goalak-v10  2026-08-15  v1.6 owner design pass: 3D bottom nav (gradient bar, gold hairline, raised glowing orb on the active tab, custom SVG icons - fantasy star replaced with an FPL-style jersey); leaderboard podium (top-3 with crown + gold/silver/bronze avatar rings); "Predict now" hero card with the live count of open UCL matches.
   goalak-v9   2026-08-15  v1.5: (a) install/download option visible like the WC app - dismissible install bar above the bottom nav (native prompt when offered, clear AR/EN instructions otherwise) + Settings install row always shown when not installed; (b) CHAT ported - new دردشة nav tab, fresh goalak_room textdb key with the WC room rules (80-message cap, dedupe by id, wipe guard, verify-after-write), fixed composer, unread badge, 12s poll in-tab + background badge checks.
   goalak-v8   2026-08-15  v1.4 WC-app essentials (owner call-outs): LIVE NOW strip (today's in-play matches across all leagues, fresh even while browsing other days); Arabic club names everywhere (~150-club FilGoal-register map, owner to validate spellings); header sign-in button + account row in Settings; favourite club (signup + Settings picker, leaderboard/userchip badges, home hero card with the club's next fixture); "التفاصيل" hint on live/finished rows pointing to the goals/cards timeline modal.
   goalak-v7   2026-08-15  v1.3: predictions now UCL-ONLY (owner call; qualifying play-offs predictable now, league phase auto-follows the draw); new third bottom-nav tab GOALAK Fantasy showing a branded "قريبًا / Soon" teaser only.
   goalak-v6   2026-08-14  v1.2: web-push handlers (payload-driven, WC-style) + badge icon precached; textdb bypassed so live data and subs never get cached.
   goalak-v5   2026-08-14  v1.2: Bundesliga added; prediction game (accounts + picks + leaderboard, goalak_* textdb keys); country flag images via flagcdn (bypassed here); readability scale-up; bottom nav; install row; Android back handling.
   goalak-v4   2026-08-14  Brand package integration: official Goal Gate mark (header + favicon), aubergine app icons from the owner's brand package, Alexandria wordmark font.
   goalak-v3   2026-08-14  v1.1 WC-app feature port: settings sheet (lang/theme/timezone/12-24h), light theme, TZ-aware times + live clock bar, compact one-screen league rail, stats hero tiles, GF/GA standings columns.
   goalak-v2   2026-08-14  QA pass: WCup navy palette; precise shell matching vs SW scope; non-ok responses fall back to cached shell; redirected responses re-wrapped before use/caching; cache writes tied to event lifetime.
   goalak-v1   2026-08-14  v1.0 initial build: 7 leagues, all-leagues day view, league pages (matches / table / stats), AR/EN RTL.
*/
const CACHE = "goalak-v65";
/* top-clubs.js is a static DATA file (last season's top five per league + the ESPN competition-id
   map). It is cache-first like every other asset here, so it refreshes on the next CACHE bump —
   which is the right cadence: the club list only changes once a season. */
const SHELL = ["./", "index.html", "manifest.json", "icon-192.png", "icon-512.png", "icon-180.png", "favicon.svg", "logo-head.svg", "logo-mark-pos.svg", "logo-mark-rev.svg", "badge.png", "top-clubs.js"];
/* Third-party hosts are never intercepted (live data + shared state must ride the network). */
const BYPASS = /espn\.com|espncdn\.com|googleapis\.com|gstatic\.com|flagcdn\.com|textdb\.online|workers\.dev/;

self.addEventListener("install", e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(SHELL)).catch(() => {}));
  self.skipWaiting();
});

self.addEventListener("activate", e => {
  e.waitUntil(
    caches.keys()
      .then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

function isShellReq(req) {
  if (req.mode === "navigate") return true;
  const scopePath = new URL(self.registration.scope).pathname;
  const p = new URL(req.url).pathname;
  return p === scopePath || p === scopePath + "index.html";
}

/* Responses that arrived via redirect cannot be replayed for navigations; re-wrap the body. */
async function unredirect(r) {
  if (!r.redirected) return r;
  const b = await r.blob();
  return new Response(b, { status: 200, headers: { "Content-Type": r.headers.get("Content-Type") || "text/html" } });
}

/* ===== Web Push ===== payload (JSON) from the goalak-push Worker:
   { title, body, icon?, badge?, tag, renotify?, silent?, url } */
self.addEventListener("push", e => {
  let d = {};
  try { d = e.data ? e.data.json() : {}; }
  catch (_) { try { d = { title: "Goallak", body: e.data.text() }; } catch (__) { d = {}; } }
  const opts = {
    body: d.body || "",
    icon: d.icon || "./icon-192.png",
    badge: d.badge || "./badge.png",
    tag: d.tag || undefined,
    renotify: d.renotify != null ? !!d.renotify : !!d.tag,
    silent: !!d.silent,
    data: { url: d.url || "./" },
    vibrate: d.silent ? undefined : [80, 40, 80]
  };
  e.waitUntil(self.registration.showNotification(d.title || "Goallak", opts));
});
self.addEventListener("notificationclick", e => {
  e.notification.close();
  const target = (e.notification.data && e.notification.data.url) || "./";
  e.waitUntil((async () => {
    const wins = await clients.matchAll({ type: "window", includeUncontrolled: true });
    for (const c of wins) {
      if ("focus" in c) { try { await c.focus(); if ("navigate" in c) { try { await c.navigate(target); } catch (_) {} } return; } catch (_) {} }
    }
    if (clients.openWindow) { try { return await clients.openWindow(target); } catch (_) {} }
  })());
});

self.addEventListener("fetch", e => {
  const url = e.request.url;
  if (e.request.method !== "GET" || BYPASS.test(url)) return;
  /* never let the worker mediate its own script — the update path must always hit the network */
  if (new URL(url).pathname.endsWith("sw.js")) return;
  if (isShellReq(e.request)) {
    /* network-first with no-store so every deploy shows on the next open; cache is the offline fallback */
    e.respondWith((async () => {
      try {
        let r = await fetch(url, { cache: "no-store" });
        if (!r.ok) throw new Error("http " + r.status);
        r = await unredirect(r);
        const cp = r.clone();
        e.waitUntil(caches.open(CACHE).then(c => c.put("index.html", cp)).catch(() => {}));
        return r;
      } catch (_) {
        const m = await caches.match("index.html");
        return m || caches.match("./");
      }
    })());
    return;
  }
  /* static assets: cache-first */
  e.respondWith((async () => {
    const m = await caches.match(e.request);
    if (m) return m;
    const r = await fetch(e.request);
    if (r && r.ok && !r.redirected) {
      const cp = r.clone();
      e.waitUntil(caches.open(CACHE).then(c => c.put(e.request, cp)).catch(() => {}));
    }
    return r;
  })());
});
